WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.Forms;

namespace WebApp.Controllers;

public class ContactsController : Controller
{
	public IActionResult Index()
	{
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> Index(ContactForm form)
	{
		if (ModelState.IsValid)
		{
			using var http = new HttpClient();

			var result = await http.PostAsJsonAsync("https://localhost:7230/api/Contact/Add?key=755d128a-d2ae-43f9-a521-41712709f1b5", form);

			if (result.IsSuccessStatusCode)
			{
                return RedirectToAction("Index", "Home");
            }
        }

		return View(form);
	}
}

WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels.Login;

namespace WebApp.Controllers;

public class LoginController : Controller
{
	public IActionResult Index()
	{
		return View();
	}

    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
	public async Task<IActionResult> Login(LoginViewModel viewModel)
	{
		if (ModelState.IsValid)
		{
			using var http = new HttpClient();

			var result = await http.PostAsJsonAsync("https://localhost:7230/api/Authentication/Login", viewModel);
			
			if (result.IsSuccessStatusCode)
			{
                var token = await result.Content.ReadAsStringAsync();

                HttpContext.Response.Cookies.Append("accessToken", token, new CookieOptions
                {
                    HttpOnly = true,
                    Secure = true,
                    Expires = DateTime.Now.AddDays(1)
                });

                return RedirectToAction("MyPage", "User");
            }
        }

		ModelState.AddModelError("", "Incorrect email or password");

		return View(viewModel);
	}

    [HttpPost]
    public IActionResult Logout(string token)
    {
        Response.Cookies.Delete(token);

        return RedirectToAction("Index", "Home");
    }
}

WebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class ProductController : Controller
{
	public async Task<IActionResult> Index()
	{
		using var http = new HttpClient();
		var result = await http.GetFromJsonAsync<IEnumerable<CollectionItemModel>>("https://localhost:7230/api/products?key=755d128a-d2ae-43f9-a521-41712709f1b5");

		return View(result);
	}

	public async Task<IActionResult> Details(int articleNumber)
	{
		using var http = new HttpClient();
		var result = await http.GetFromJsonAsync<CollectionItemModel>($"https://localhost:7230/api/products/id/{articleNumber}?key=755d128a-d2ae-43f9-a521-41712709f1b5");

		return View(result);
	}
}

WebApp/Views/Shared/Partials/_CollectionItemPartial.cshtml
@model WebApp.Models.CollectionItemModel

<div class="item">
	<div class="image-section">
		<img src="@Model.ImageUrl" alt="@Model.ProductName">
		<div class="menu">
			<div class="icons">
				<button class="link">
					<i class="fa-regular fa-code-compare"></i>
				</button>
				<button class="link">
					<i class="fa-regular fa-heart"></i>
				</button>
				<button class="link">
					<i class="fa-regular fa-bag-shopping"></i>
				</button>
			</div>
			<a asp-action="Details" asp-controller="Product" asp-route-articleNumber="@Model.ArticleNumber" class="btn-theme">QUICK VIEW</a>
		</div>
	</div>
    
	<div class="body-section">
		<div class="body-section">
			<div class="title">@Model.ProductName</div>
			<partial name="~/Views/Shared/Partials/_StarRatingPartial.cshtml" model="@Model?.StarRating" />
			<div class="price">$@Model.Price</div>
		</div>
	</div>
</div>

WebApp/Views/Shared/Partials/_CollectionPartial.cshtml
@model WebApp.Models.CollectionModel

<section class="collection-grid">
    <div class="container">
        <h1 class="title">@Model.Title</h1>

        <div class="item-collection">

            @foreach (var item in Model.CollectionItems)
            {
                <partial name="~/Views/Shared/Partials/_CollectionItemPartial.cshtml" model="item" />
            }

        </div>
        <div class="load-more d-flex justify-content-center">
            <button class="btn-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_FooterPartial.cshtml
<footer>
	<p class="fw-semibold text-center">&copy; @DateTime.Now.Year Fixxo. All Rights Reserved</p>
</footer>

WebApp/Views/Shared/Partials/_HeaderPartial.cshtml
@inject IHttpContextAccessor accessor;

<header>
    <div class="container">
        <a id="logotype" asp-controller="Home" asp-action="Index">Fixxo.</a>

        <div id="menu" class="hide">
            <nav class="menu-links links">
                <a class="link @(accessor.HttpContext.Request.Path.Value == "/" ? "active" : "")" asp-controller="Home" asp-action="Index">HOME</a>
                <a class="link @(accessor.HttpContext.Request.Path.Value == "/Product" ? "active" : "")" asp-controller="Product" asp-action="Index">PRODUCTS</a>
                <a class="link @(accessor.HttpContext.Request.Path.Value == "/Contacts" ? "active" : "")" asp-controller="Contacts" asp-action="Index">CONTACT</a>
            </nav>
            <nav class="menu-icons icons">
                <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-search"></i></a>
                <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-code-compare"></i></a>
                <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-heart"></i></a>
                <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-bag-shopping"></i></a>
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="link ms-5" asp-controller="User" asp-action="MyPage"><i class="fa-regular fa-user"></i></a>
                }
                else
                {
                    <a class="link ms-5" asp-controller="Login" asp-action="Index"><i class="fa-regular fa-user"></i></a>
                }
            </nav>
        </div>

        <div id="toggle-icon" class="toggle icons">
            <button class="link" data-option="toggle" data-target="#menu"><i class="fa-regular fa-bars"></i></button>
            <button class="btn-white" data-option="toggle" data-target="#menu"><i class="fa-regular fa-bars"></i></button>
        </div>

    </div>
</header>   

WebApp/Views/Shared/Partials/_ShowcasePartial.cshtml
@model WebApp.Models.ShowcaseModel

@if (Model != null)
{
    <section class="showcase">
        <div class="container">
            <div class="content">
                <div class="title-1">@Model.Ingress</div>
                <div class="title-2">@Model.Title</div>
                <button class="btn-theme">@Model.ButtonText</button>
            </div>
            <div class="content-image">
                <img src="@Model.ImageUrl" alt="@Model.Title">
            </div>
        </div>
    </section>
}

WebApp/Views/Shared/Partials/_SpecialOffersPartial.cshtml
<div class="offer-grid container-fluid">
    <img id="office-style" src="./images/office-style.png" alt="" />

    <div class="offer">
        <div class="red-border">
            <div class="content">
                <h1>50% Offer</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, ipsam quo voluptatum facere iure fuga. Necessitatibus quasi voluptatem delectus nam?</p>
                <button className="btn-white">FLASH SALE</button>
            </div>
        </div>
    </div>
    <img id="party-style" src="./images/party-style.png" alt="" />
</div>

WebApp/Views/Shared/Partials/_StarRatingPartial.cshtml
@model int

<div class="star-rating">

	@for (int i = 0; i < 5; i++)
	{
		string rating = "";

		if (Model <= i)
			rating = "fa-regular";
		else
			rating = "fa-solid";

		<i class="fa-sharp fa-star @rating"></i>
	}
</div>